name: rezept_nachkochen
description: Rezeptvideos von Facebook & Co. teilen und als Schritt-für-Schritt-Anleitung nachkochen.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  receive_sharing_intent: ^1.8.1
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  image_picker: ^1.2.3
  google_fonts: ^8.1.0
  google_sign_in: 6.3.0
  web: ^1.1.1
  supabase_flutter: ^2.16.0
  syncfusion_flutter_pdf: ^34.1.32
  file_selector: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon_android.png
  adaptive_icon_background: "#FFE8D6"
  adaptive_icon_foreground: assets/icon/app_icon.png
  web:
    generate: true
    image_path: assets/icon/app_icon_android.png
    background_color: "#FFE8D6"
    theme_color: "#2F6F4E"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
